### ISSUE TITLE
Release the files and also documentation

### ISSUE THREAD

**Issue by mrocr** [koelscha/hackathon#1]
@koelscha @bnunamak 
Can you release the code files and scripts.
What are the requirements to run the code?
Can you add some documentation on how to use the code.
Can you add some examples along with training data.

**Comment by harshgrovr** [comment]
How to set up the environment to execute this code in Ubuntu?

**Comment by mrocr** [comment]
@koelscha @bnunamak 
can you upload the requirements
`conda env export > environment.yml` or `pip freeze > requirements.txt`

Also, examples on how to use your code.
